<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <!-- Die Adresse dieses Projekts. Diese drei Angaben zusammen sind eindeutig. -->
  <groupId>at.htl.shkodra</groupId>
  <artifactId>sew5</artifactId>
  <version>0.2.0</version>


  <!-- TODO Uebung 1: Java-Version und Encoding ergaenzen.
       Ohne die Encoding-Zeile werden Umlaute und ë auf manchen Rechnern
       zu Fragezeichen.

  <properties>
    ...
  </properties>
  -->
  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <!-- TODO Uebung 3: Die Gson-Bibliothek eintragen.
       Den Block findet ihr auf search.maven.org zum Kopieren.

  <dependencies>
    ...
  </dependencies>
  -->
    <dependencies>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.14.0</version>
        </dependency>
    </dependencies>

</project>
